// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl1_kjaFcygStaCxL68kofmInjvc8au1g',
    appId: '1:936618528132:web:390faaf3c3407d4be361d1',
    messagingSenderId: '936618528132',
    projectId: 'adhd-svedin',
    authDomain: 'adhd-svedin.firebaseapp.com',
    storageBucket: 'adhd-svedin.firebasestorage.app',
    measurementId: 'G-1S90L35EVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuofSirjbIMw_3LsoFGgOpaLQRKFt84fY',
    appId: '1:936618528132:android:b07f1679bc1f452be361d1',
    messagingSenderId: '936618528132',
    projectId: 'adhd-svedin',
    storageBucket: 'adhd-svedin.firebasestorage.app',
  );
}
